In [16]:
%run main_reg_cla.py


epoch #0 loss: 1.7624417626488832e+16
epoch #1 loss: 14642560630784.0
epoch #2 loss: 162054553600.0
epoch #3 loss: 536756224.0
epoch #4 loss: 2768896.0
epoch #5 loss: 16384.0
epoch #6 loss: 0.0
epoch #7 loss: 0.0
epoch #8 loss: 0.0
epoch #9 loss: 0.0
epoch #10 loss: 0.0
epoch #11 loss: 0.0
epoch #12 loss: 0.0
epoch #13 loss: 0.0
epoch #14 loss: 0.0
epoch #15 loss: 0.0
epoch #16 loss: 0.0
epoch #17 loss: 0.0
epoch #18 loss: 0.0
epoch #19 loss: 0.0
train success!
total =  822
4
2
RTT实际增大，预测增大的次数： 0.0
RTT实际增大，预测减小的次数： 0.0
RTT实际减小，预测增大的次数： 0.0
RTT实际减小，预测减小的次数： 0.0

精确率 = nan%
召回率 = nan%


/home/zhijian/workspace_fast/workspace/Time-Series-Forecasting/rtt-prediction/LSTM-based/main_reg_cla.py:110: RuntimeWarning: invalid value encountered in float_scalars
  print('精确率 = {}%'.format(round(confusion[0][0]/(confusion[0][0]+confusion[1][0]) * 100, 2)))
/home/zhijian/workspace_fast/workspace/Time-Series-Forecasting/rtt-prediction/LSTM-based/main_reg_cla.py:111: RuntimeWarning: invalid value encountered in float_scalars
  print('召回率 = {}%'.format(round(confusion[0][0]/(confusion[0][0]+confusion[0][1]) * 100, 2)))


In [17]:
import pandas
train_df = pandas.read_csv('./data/train.csv')
raw_data = train_df['rtt'].values
raw_data

array([ 47., 102., 140., ..., 123., 148., 133.])

In [46]:
raw_data = train_df[train_df['building_id'].apply(lambda x:x==1)&
             train_df['meter_reading'].apply(lambda x:x>0)&
             train_df['meter'].apply(lambda x:x==0)]

In [7]:
raw_data.values[200:]

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [1]:
import torch
import numpy as np

In [74]:
a = np.array([1,2,3])
b = a[2:3]

In [78]:
t1 = torch.from_numpy(b)
print(t1[0] > )

tensor(3)


In [7]:
a = []
a.append([0.4,0.6])
a.append([0.8,0.2])
a = torch.tensor(a)
a

tensor([[0.4000, 0.6000],
        [0.8000, 0.2000]])

In [11]:
_, pred = torch.max(a,dim=1)

In [12]:
pred

tensor([1, 0])

In [14]:
a = np.array([1,2,3])
b = np.array([1,1,0])
a*b

array([1, 2, 0])

In [41]:
import json

In [42]:
a = '1'*1400

In [46]:
data = {}
data['source_ip'] = '10.0.0.1'
data['des_ip'] = '10.0.0.2'
data['des_port'] = '8890'
data['data'] = a


In [47]:
df = json.dumps(data).encode()

In [48]:
len(df)

1480

In [58]:
import time
int((time.time()%(10**3))*1000000) #ns

851820014

In [23]:
a = 1.43134
round(a,5)
import numpy as np
np.random.randn()

-1.3092033499035045

In [36]:
import numpy as np

Bandwidth_base = np.arange(15,101,5)
Bandwidth_seq = []

for bd in Bandwidth_base:
    err = np.random.randn()
    Bandwidth_seq.append(bd+2*err)

for bd in Bandwidth_base[::-1]:
    err = np.random.randn()
    Bandwidth_seq.append(bd+2*err)

print(Bandwidth_seq)


[14.45880869830878, 18.007506225598412, 21.27515393221405, 30.022137371767947, 36.505817057180444, 40.8862498956218, 45.60714178346188, 51.96743154003641, 55.793353941982936, 62.455061508038625, 63.77659619579389, 70.71706447660809, 73.22408382626914, 83.91492600351039, 87.58272240571223, 92.41821212483008, 95.276039293807, 97.94532626003101, 99.76634556651652, 94.34917286884146, 90.83324924644465, 82.86824597912769, 78.73303309983186, 78.10195770515656, 69.79088361745895, 67.45308337424052, 60.02116722730889, 53.31839138148113, 50.31383792959676, 42.087057569492856, 39.8534073648059, 35.06390001610491, 27.021366063790392, 22.97872023180355, 19.09474181512331, 13.783536019492374]
